brand = "Barnes & Noble"
codename = "ovation"
name = "Barnes & Noble Nook HD+"
roms = []

[[recoveries]]
id = "twrp"
maintainer = "airend"

[specs]
cpu = "Not found"
weight = "Not found"
year = "Not found"
os = "Not found"
chipset = "Not found"
gpu = "Not found"
sensors = "Not found"
batlife = "Not found"
internalmemory = "Not found"
